name: IOSteinPerks
version: 0.41
description: Perks for IOStein Server
author: nimble0
api-version: 1.16

depend: [ProtocolLib]

main: de.nimble.iostein.PerksPlugin

commands:
  perks:
    description: Command for perks
    usage: /<name>
    permission: perks.admin
    permission-message: You don't have the right permission to do this
  spawnNPC:
    description: Spawns a NPC
    usage: /spawnNPC
    permission: perks.npc.spawn
    permission-message: You don't have the right permission to do this