name: IOSteinPerks
version: 0.3
description: Perks for IOStein Server
author: nimble0

main: de.nimble.iostein.PerksPlugin

commands:
  perks:
    description: Command for perks
    usage: /<name>
    permission: perks.admin
    permission-message: You don't have the right permission to do this